Solved pingpong between processes
Arslanka-Educational/os-xv6-riscv pull request #1
Opened 2023-10-14 13:30 UTC by Arslanka

2023-11-05 16:53 UTC, vityaman requested changes
Not so bad, but some small changes are needed

2023-11-05 16:53 UTC, vityaman commented on kernel/buddy.c
> + char b = array[index / 16];
not clear why `array[index / 16]` here. It looks like `bit_set`, but in `bit_set` logic is understandable, here is not

2023-11-05 16:53 UTC, vityaman commented on kernel/buddy.c
> +    printf("  alloc:");
not alloc, but xor_alloc_buddy

2023-11-05 16:53 UTC, vityaman commented on kernel/file.c
>    acquire(&ftable.lock);
Do we really need to acquire this lock here?

2023-11-05 16:53 UTC, vityaman commented on kernel/proc.c
> +      if (p->pid == pid && !proc->killed) {
race condition is here

2023-11-05 16:53 UTC, vityaman commented on kernel/sysproc.c
> +  uint64 return_value = 0;
why return value is zero initially, while other variables uninitialized?

2023-11-05 16:53 UTC, vityaman commented on user/pingpong.c
> +        read(fd[0], buf, sizeof buf);
It is better to handle errors, not ignoring them

2023-11-11 12:28 UTC, vityaman commented
Ping

2023-11-11 14:22 UTC, Arslanka commented
> Ping

Pong

2023-11-11 14:35 UTC, vityaman commented on kernel/proc.c
> +      if (p->pid == pid && !proc->killed) {
wtf?! It should not work!

2023-11-11 14:37 UTC, vityaman commented on kernel/proc.c
> +      if (p->pid == pid && !proc->killed) {
Here, caller_proc -- myproc, not an array,
proc is an array. Also proc->killed is an mistake p->killed is correct

2023-11-11 14:38 UTC, vityaman commented on kernel/file.c
>    acquire(&ftable.lock);
It is better to lock only file, not all files in the system

2023-11-26 18:30 UTC, merged